### PR TITLE
Added option noProfile incl. tests and docs.

### PR DESCRIPTION
**Pull request by atufkas**
Hi there,

I'm kindly asking you to review and accept a pull request adding the option _noProfile_ which allows to remove embedded profile data (im/gm `+profile "*"`).

Example:

````
.pipe(imageResize({
  width : 200,
  quality: 0.8,
  noProfile: true
}))
````
I'm confident this is a **very useful option for this kind of "convenient high level wrapper"** on top of gm (+ gulp-gm). Most people probably want to do quick and easy web image preview and thumbnail creation jobs where **profile data is normally unwanted and may consume a lot of space and bandwidth**. For simplicity reasons I also avoided implementing a version which allows to pass parameter values all the way down to gm/im `+profile` or even `-profile`, thus expecting users are willing to remove all or no profiles. 

The option defaults to `false` though to keep BC.

Tests manipulating an additional image fixture with profile data are included. It's a bit tricky to detect existing profiles with _identify_ so for actually asserting removal of profile data I had to enforce a second gm instance which makes use of the ImageMagick implementation, see test file: `var gm_im = ...`.

Docs (README) is updated as well.

Maybe this should also be backported to _grunt-image-resize_ ...?

Cheers,
Matthias from Hamburg

### CODE REVIEW

**Comment by atufkas** [comment]
Ist this module still actively maintained or abandoned...?

**Comment by tmbo** [comment]
@normanrz mind having a look at this PR?

**Comment by normanrz** [comment]
Hi @atufkas, sorry for the long wait. Thank you for your great PR.
Unfortunately, the tests don't pass because `test/fixtures/hamburg.jpg` is missing in this PR. Could you add the fixture and expected image files? Then I can merge your PR.

We'd be happy to add you as a collaborator to this repo if you're interested. We're not using this module in our current projects, so we'd appreciate help to maintain it.

**Comment by atufkas** [comment]
Ooops, sorry. Sure, here you go...

**Comment by normanrz** [comment]
Thanks!

**Comment by atufkas** [comment]
Oh, yes, regarding adding me as collaborator: Yes, feel free to do so. There isn't too much activity on this repo and therefore I see no problem in helping out maintaining it – at least for a while. 

Cheers,
Matthias

**Pull request merged**
